language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./fsm_test

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"